// Loan modification requests: pick a modification type, add notes, and the app produces a
// print-ready PDF populated with everything it knows about the loan — and logs the request
// on the loan's record.
import { useState } from 'react'
import { supabase, DbLoan, Guarantor, Org, money } from './supabase'
import { toast, currentUserName } from './dialogs'
import { fmtDate } from './Loans'
import { Ico } from './Icons'

export const MOD_TYPES = [
  'Extend draw period',
  'Extend maturity',
  'Reduce loan amount',
  'Increase loan amount',
  'Add co-borrower',
  'Remove co-borrower',
  'Rate modification',
  'Payment deferral',
  'Release collateral',
] as const

const esc = (s: unknown) => String(s ?? '—').replace(/&/g, '&amp;').replace(/</g, '&lt;')

function buildPdfHtml(org: Org, loan: DbLoan, guarantors: Guarantor[], modType: string, notes: string, requestedBy: string) {
  const row = (k: string, v: unknown) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  return `<!doctype html><html><head><meta charset="utf-8"><title>Loan Modification Request — ${esc(loan.loan_number)}</title>
<style>
  @page { margin: 1in; }
  body { font-family: -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif; color: #111; font-size: 12.5px; line-height: 1.45; margin: 0; }
  header { display: flex; justify-content: space-between; align-items: baseline; border-bottom: 2px solid #111; padding-bottom: 10px; margin-bottom: 18px; }
  h1 { font-size: 19px; margin: 0; }
  .bank { font-size: 13px; font-weight: 700; }
  h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .6px; color: #555; margin: 22px 0 6px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 6px 8px; border-bottom: 1px solid #ddd; vertical-align: top; }
  td:first-child { width: 220px; color: #555; }
  .req { border: 1.5px solid #111; padding: 12px 14px; margin-top: 6px; }
  .req b { font-size: 14px; }
  .notes { min-height: 70px; white-space: pre-wrap; }
  .sig { display: flex; gap: 40px; margin-top: 44px; }
  .sig div { flex: 1; border-top: 1px solid #111; padding-top: 6px; font-size: 11.5px; color: #555; }
  footer { margin-top: 34px; font-size: 10.5px; color: #888; }
</style></head><body>
<header><div><h1>Loan Modification Request</h1></div><div class="bank">${esc(org.name)}</div></header>
<table>
  ${row('Date of request', today)}
  ${row('Requested by', requestedBy)}
  ${row('Loan number', loan.loan_number)}
  ${row('Borrower', loan.customers?.company ?? loan.customers?.name)}
  ${row('Contact', `${loan.customers?.name ?? '—'} · ${loan.customers?.email ?? 'no email'} · ${loan.customers?.phone ?? 'no phone'}`)}
</table>

<h2>Requested modification</h2>
<div class="req">
  <b>${esc(modType)}</b>
  <div class="notes">${esc(notes) || 'No additional notes provided.'}</div>
</div>

<h2>Current loan terms</h2>
<table>
  ${row('Loan type', loan.type)}
  ${row('Original commitment', money(Number(loan.amount)))}
  ${row('Current balance', loan.current_balance == null ? '—' : money(Number(loan.current_balance)))}
  ${row('Rate', `${loan.rate ?? '—'}${loan.rate_floor ? ` · floor ${loan.rate_floor}` : ''}`)}
  ${row('Payment structure', loan.payment_type)}
  ${row('Next payment', loan.next_payment_amount ? `${money(Number(loan.next_payment_amount))} on ${fmtDate(loan.next_payment_date)}` : '—')}
  ${row('Term / amortization', loan.term ?? '—')}
  ${row('Origination date', fmtDate(loan.origination_date))}
  ${row('Draw period ends', fmtDate(loan.draw_period_end))}
  ${row('Maturity date', fmtDate(loan.maturity))}
  ${row('Collateral', loan.collateral)}
  ${row('Relationship manager', loan.rm)}
</table>

<h2>Guarantors</h2>
<table>
  ${guarantors.length
    ? guarantors.map(g => row(g.name, `${g.guarantee_pct ? `${g.guarantee_pct}% ` : ''}${g.guarantee_type ?? ''} · PFS ${fmtDate(g.pfs_date)}${g.net_worth ? ` · net worth ${money(Number(g.net_worth))}` : ''}`)).join('')
    : row('None on record', '')}
</table>

<div class="sig">
  <div>Borrower signature / date</div>
  <div>Guarantor signature / date</div>
  <div>Lender approval / date</div>
</div>
<footer>Generated by NoteSolo on ${today}. This request is subject to credit approval and does not modify the loan until executed by all parties.</footer>
</body></html>`
}

// Print via a hidden same-page iframe — immune to pop-up blockers.
function printHtml(html: string) {
  const frame = document.createElement('iframe')
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0'
  frame.srcdoc = html
  frame.onload = () => {
    frame.contentWindow?.focus()
    frame.contentWindow?.print()
    setTimeout(() => frame.remove(), 60000)
  }
  document.body.appendChild(frame)
}

export function ModifyButton({ org, loan, small }: { org: Org; loan: DbLoan; small?: boolean }) {
  const [open, setOpen] = useState(false)
  const [modType, setModType] = useState<string>(MOD_TYPES[0])
  const [notes, setNotes] = useState('')
  const [busy, setBusy] = useState(false)

  const generate = async (e: React.FormEvent) => {
    e.preventDefault()
    setBusy(true)
    const [{ data: g }, requestedBy] = await Promise.all([
      supabase.from('guarantors').select('*').eq('loan_id', loan.id),
      currentUserName(),
    ])
    const html = buildPdfHtml(org, loan, (g as Guarantor[]) ?? [], modType, notes, requestedBy)
    printHtml(html)
    // On the record: every modification request becomes part of the loan's history.
    await supabase.from('loan_notes').insert({
      org_id: org.id, loan_id: loan.id,
      body: `[Modification request] ${modType}${notes ? ` — ${notes}` : ''}`,
      author: requestedBy, created_by: (await supabase.auth.getUser()).data.user?.id,
    })
    setBusy(false)
    setOpen(false)
    setNotes('')
    toast('Modification request PDF ready — logged on the loan')
  }

  return (
    <>
      <button
        className={small ? 'btn-light' : 'btn-dark'}
        onClick={e => { e.stopPropagation(); setOpen(true) }}
        title="Create a loan modification request PDF"
      >
        {small ? 'Modify' : <><Ico.doc /> Modification PDF</>}
      </button>
      {open && (
        <div className="dlg-overlay" onClick={e => { e.stopPropagation(); setOpen(false) }}>
          <form className="dlg" onClick={e => e.stopPropagation()} onSubmit={generate} style={{ width: 480 }}>
            <b>Loan modification request</b>
            <p className="small" style={{ margin: '4px 0 0' }}>
              {loan.loan_number} · {loan.customers?.company} · {money(Number(loan.amount))}
            </p>
            <label className="dlg-label">Modification type
              <select value={modType} onChange={e => setModType(e.target.value)}
                style={{ display: 'block', width: '100%', marginTop: 6, borderRadius: 8, padding: '9px 11px', font: 'inherit', background: 'var(--card-2)', color: 'var(--ink)', border: '1px solid var(--line)' }}>
                {MOD_TYPES.map(t => <option key={t}>{t}</option>)}
              </select>
            </label>
            <label className="dlg-label">Notes
              <textarea rows={4} value={notes} onChange={e => setNotes(e.target.value)}
                placeholder="e.g. Borrower requests 6-month draw period extension to complete operatory build-out; contractor delay letter attached."
                style={{ display: 'block', width: '100%', marginTop: 6, borderRadius: 8, padding: '9px 11px', font: 'inherit', background: 'var(--card-2)', color: 'var(--ink)', border: '1px solid var(--line)', resize: 'vertical' }} />
            </label>
            <div className="dlg-actions">
              <button type="button" className="btn-light" onClick={() => setOpen(false)}>Cancel</button>
              <button type="submit" className="btn-dark" disabled={busy}>{busy ? 'Building…' : 'Create PDF'}</button>
            </div>
          </form>
        </div>
      )}
    </>
  )
}
